# データベース起動
version: '3.8'
services:
  db:
    container_name: 'local-oder-taking-system-db'
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=template
      # - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '0.0.0.0:15432:5432'
